### ISSUE TITLE
How to change auto-prefixer to behave like Styled Components or Emotion?

### ISSUE THREAD

**Issue by etc-tiago** [kripod/otion#14]
## Motivation

Browsers process styles in different ways, and like StyledComponents or Emotion already do, apply styles for the browser to process the style as expected.

## Details

Currently the style
```js
css({
boxShadow: '10px 44px 5px 0px rgba(0,0,0,0.75)'
})
```

is transformed into the class

```css
._yf6uil._yf6uil {
    box-shadow: 10px 44px 5px 0px rgba(0,0,0,0.75);
}
```

and it could add browser compatibility

```css
._yf6uil._yf6uil {
    -webkit-box-shadow: 10px 44px 5px 0px rgba(0,0,0,0.75);
    -moz-box-shadow: 10px 44px 5px 0px rgba(0,0,0,0.75);
    box-shadow: 10px 44px 5px 0px rgba(0,0,0,0.75);
}
```

Are there any plans to add this feature in the future?
