### ISSUE TITLE
Re-inserted conditional rules shouldn’t cause style duplication

### ISSUE THREAD

**Issue by kripod** [kripod/otion#43]
## Motivation

When re-inserting a style for precedence management, the old rule isn’t removed from the stylesheet. This may cause some duplication when media or feature queries are used frequently.

**Comment by eddyw** [comment]
👋  When a conditional rule is re-inserted, it shouldn't be removed or duplicated but it should be generated with a different classname. This also applies when they aren't re-inserted in this case:

Take for example this:
```javascript
export default function IndexPage(): JSX.Element {
  return (
    <React.StrictMode>
      <h1>Hello, world!</h1>
      <p
        className={css({
          "@media": {
            "(min-width: 5px)": { color: "blue" },
            "(min-width: 4px)": { color: "green" },
          },
        })}
      >
        Conditional rule precedence management test #1, should be green
      </p>
    </React.StrictMode>
  );
}
```
It is `green` and generates the following CSS code:
```css
@media(min-width:5px){._bxnxkd{color:blue}}
@media(min-width:4px){._107ye90{color:green}}
```
which is the correct order in which they were defined.
Now try this:
```javascript
export default function IndexPage(): JSX.Element {
  return (
    <React.StrictMode>
      <h1>Hello, world!</h1>
      <p
        className={css({
          "@media": {
            "(min-width: 4px)": { color: "green" },
            "(min-width: 5px)": { color: "blue" },
          },
        })}
      >
        Conditional rule precedence management test #2, should be blue
      </p>
    </React.StrictMode>
  );
}
```
It is `blue` and generates again in the CSS in correct order:
```css
@media(min-width:4px){._107ye90{color:green}}
@media(min-width:5px){._bxnxkd{color:blue}}
```
However, because re-inserted conditional rules have the same class-name, this happens:
```javascript
export default function IndexPage(): JSX.Element {
  return (
    <React.StrictMode>
      <h1>Hello, world!</h1>
      <p
        className={css({
          "@media": {
            "(min-width: 5px)": { color: "blue" },
            "(min-width: 4px)": { color: "green" },
          },
        })}
      >
        Conditional rule precedence management test #1, should be green
      </p>
      <p
        className={css({
          "@media": {
            "(min-width: 4px)": { color: "green" },
            "(min-width: 5px)": { color: "blue" },
          },
        })}
      >
        Conditional rule precedence management test #2, should be blue
      </p>
    </React.StrictMode>
  );
}
```
Both are `green` and CSS is:
```css
@media(min-width:5px){._bxnxkd{color:blue}}
@media(min-width:4px){._107ye90{color:green}}
```

The expected result should be:
```css
@media(min-width:5px){._bxnxkd{color:blue}} /* SourceIndex: 0 */
@media(min-width:4px){._107ye90{color:green}} /* SourceIndex: 1 */
@media(min-width:4px){._NEW_CLS_0{color:green}} /* SourceIndex: 0 */
@media(min-width:5px){._NEW_CLS_1{color:blue}} /* SourceIndex: 1 */
```
I couldn't understand very well what `createInstance` does (the terms used could use some comments 😅 ) but ..
The `hash` method could also use `precedence` and `ruleIndex` to generate the classname (sort of like `hash(declarations + precedence + ruleIndex || 0))`, so you could always check if a rule has been inserted instead of re-inserting the rule and removing the old one which would break styling (as shown above)
